### ISSUE TITLE
Falta de chequeo

### ISSUE THREAD

**Issue by lbaldi** [ProyectoAconcagua/l10n_ar_point_of_sale_v7#4]
Falta de chequeo para account.invoice , account.voucher para que no te las deje validar en caso estas tengan un total en negativo.

![negativo](https://cloud.githubusercontent.com/assets/2495544/3236033/1b951c9c-f0d9-11e3-91b3-a9d4cec5304a.jpg)

**Comment by sebastiken** [comment]
@lbaldi con respecto al chequeo de valor negativo en account.voucher ya estaba solucionado por el commit  ProyectoAconcagua/l10n_ar_account_payment_v7@1d8a1b2
Pero el tema de la factura, es verdad que el chequeo no está, tampoco está en el código base de OpenERP/Odoo. Igual viene muy bien ese chequeo.

**Comment by sebastiken** [comment]
Cerrado por #5 ya mergeado.
