### ISSUE TITLE
Problema numeracion automatica de factura

### ISSUE THREAD

**Issue by maxifochi** [ProyectoAconcagua/l10n_ar_point_of_sale_v7#6]
Hola, entiendo que el numero de factura deberia generarse automaticamente. Adjunto captura, donde se ve que creo una factura desde contabilidad, y debo ingresar si o si el numero de factura manual, lo cual supongo que no es el comportamiento esperado.
![bugnumerofacturaaconcagua](https://cloud.githubusercontent.com/assets/7989082/3390144/d4308962-fc9b-11e3-908d-24eab7360f28.png)

**Comment by sebastiken** [comment]
Maximiliano, gracias por interesarte en el Proyecto.
Te comento que los comprobantes de clientes, llámesen Facturas, NC y ND, en todos ellos la numeración es automática y de hecho no se realiza por medio del objeto **ir.sequence** ya que puede generar huecos. El código que genera la numeración automática data de la fecha 10 Nov 2011 según el commit e45372a Este código casi no cambió.
El problema que veo que estás teniendo según lo que puedo ver en el screenshot es que el punto de vento debería ser **0001** porque sino no matchea con el formato pedido _(XXXX-)_ del punto de venta. Vos lo tenés definido como **01**.
Podés agregar dos ceros más adelante, también podés proponer hacer algún cambio en esa parte del código.
En resumen, no es un error del módulo sino de configuración; pero me parece interesante la posibilidad de chequear el formato del punto de venta para que al hacer la configuración del mismo, el usuario no cometa el error de poner un formato que no es correcto y avisarle de alguna manera.

Saludos

**Comment by sebastiken** [comment]
Se cierra este Issue y se abre el correspodiente a la mejora del chequeo del _punto de venta_ #7
