### ISSUE TITLE
Manejo notas de credito [question]

### ISSUE THREAD

**Issue by maxifochi** [ProyectoAconcagua/l10n_ar_point_of_sale_v7#8]
Buenas, escribo para consultarles acerca del manejo de notas de credito.
Si estoy en lo correcto deberia manejarlas a traves del menu reembolsos al cliente es asi?
A la hora de seleccionar si es una nota de credito A o B, basta con seleccionar mi punto de venta segun corresponda?

Desde ya gracias.

**Comment by sebastiken** [comment]
@maxifochi **Notas de Crédito** es justamente **Reembolsos**, tanto al cliente como al proveedor. Es el nombre que trae del Inglés, ya que es un objeto, así como las **Facturas** que son parte del módulo _account_ de _Odoo/OpenERP_.
La elección de la denominación y el punto de venta no se debería hacer en forma manual; aunque lo permite, lo ideal es solo ingresar el _cliente/proveedor_ que tiene que tener la configuración de la _posición fiscal_ y por medio de la configuración propia que tiene el módulo, solo te va a seleccionar la **denominación** y el **punto de venta** correspondiente.

Saludos.
